f = open("somefile.txt", "r")
print_file = f.readlines()
print (print_file)
f = open("newfile.txt", "w")
f.write("I like Pizza\n")
f.write("Rudy can't have pizza\n")
f.close()
f = open("newfile.txt", "a")
f.write("I had pizza for lunch\n")
f.close()
