---
cisco3:
    hostname: cisco3.lasthop.io
    groups: 
      - cisco

cisco4:
    hostname: cisco4.lasthop.io
    groups: 
      - cisco

arista1:
    hostname: arista1.lasthop.io
    groups: 
      - arista

arista2:
    hostname: arista2.lasthop.io
    groups: 
      - arista

arista3:
    hostname: arista3.lasthop.io
    groups: 
      - arista

arista4:
    hostname: arista4.lasthop.io
    groups: 
      - arista

srx2:
    hostname: srx2.lasthop.io
    groups: 
      - juniper

nxos1:
    hostname: nxos1.lasthop.io
    groups: 
      - nxos

nxos2:
    hostname: nxos2.lasthop.io
    groups: 
      - nxos
